CREATE TABLE city(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    city_name VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT name_gt_2_char CHECK (CHAR_LENGTH(city_name) > 2)
) DEFAULT CHARSET UTF8 COMMENT '';